MODERATED_LIST_MSG	= "Moderated list."

MMUnknownListError   = "MMUnknownListError"
MMBadListError       = "MMBadListError"
MMBadConfigError     = "MMBadConfigError"

MMBadEmailError      = "MMBadEmailError"
MMMustDigestError    = "MMMustDigestError"
MMCantDigestError    = "MMCantDigestError"
MMNotAMemberError    = "MMNotAMemberError"
MMListNotReady       = "MMListNotReady"
MMNoSuchUserError    = "MMNoSuchUserError"
MMBadPasswordError   = "MMBadPasswordError"
MMNeedApproval       = "MMNeedApproval"
MMHostileAddress     = "MMHostileAddress"
MMAlreadyAMember     = "MMAlreadyAMember"
MMPasswordsMustMatch = "MMPasswordsMustMatch"
MMAlreadyDigested    = "MMAlreadyDigested"
MMAlreadyUndigested  = "MMAlreadyUndigested"
MMBadRequestId       = "MMBadRequestId"
MMWebSubscribeRequiresConfirmation = "MMWebSubscribeRequiresConfirmation"

