#!/usr/local/bin/python
# We don't need to lock in this script, because we're never going to change data.

import sys, os
f = open('/tmp/options.errs', 'a+')
sys.stderr = f # sys.stdout
sys.path.append('/home/mailman/mailman/modules')
import mm_utils, maillist, htmlformat, mm_cfg

doc = htmlformat.Document()

path = os.environ['PATH_INFO']
list_info = mm_utils.GetPathPieces(path)

if len(list_info) < 2:
    doc.AddItem(htmlformat.Header(2, "Invalid options to CGI script."))
    print doc.Format()
    sys.exit(0)

list_name = list_info[0]
user = list_info[1]

try:
  list = maillist.MailList(list_name)
except:
  doc.AddItem(htmlformat.Header(2, "%s: No such list." % list_name ))
  print doc.Format()
  sys.exit(0)

if not list._ready:
    doc.AddItem(htmlformat.Header(2, "%s: No such list." % list_name ))
    print doc.Format()
    sys.exit(0)


replacements = list.GetStandardReplacements()
replacements['<mm-digest-radio-button>'] = list.FormatOptionButton(
	mm_cfg.Digests, 1, user)
replacements['<mm-undigest-radio-button>'] = list.FormatOptionButton(
	mm_cfg.Digests, 0, user)
replacements['<mm-plain-digests-button>'] = list.FormatOptionButton(
	mm_cfg.EnableMime, 0, user)
replacements['<mm-fancy-digests-button>'] = list.FormatOptionButton(
	mm_cfg.EnableMime, 1, user)
replacements['<mm-delivery-enable-button>'] = list.FormatOptionButton(
	mm_cfg.DisableDelivery, 0, user)
replacements['<mm-delivery-disable-button>'] = list.FormatOptionButton(
	mm_cfg.DisableDelivery, 1, user)
replacements['<mm-dont-ack-posts-button>'] = list.FormatOptionButton(
	mm_cfg.AcknowlegePosts, 0, user)
replacements['<mm-ack-posts-button>'] = list.FormatOptionButton(
	mm_cfg.AcknowlegePosts, 1, user)
replacements['<mm-receive-own-mail-button>'] = list.FormatOptionButton(
	mm_cfg.DontReceiveOwnPosts, 0, user)
replacements['<mm-dont-receive-own-mail-button>'] = list.FormatOptionButton(
	mm_cfg.DontReceiveOwnPosts, 1, user)
replacements['<mm-public-subscription-button>'] = list.FormatOptionButton(
	mm_cfg.ConcealSubscription, 0, user)
replacements['<mm-hide-subscription-button>'] = list.FormatOptionButton(
	mm_cfg.ConcealSubscription, 1, user)

replacements['<mm-digest-submit>'] = list.FormatButton('setdigest', 'Submit')
replacements['<mm-unsubscribe-button>'] = list.FormatButton('unsub', 'Unsubscribe')
replacements['<mm-digest-pw-box>'] = list.FormatSecureBox('digpw')
replacements['<mm-unsub-pw-box>'] = list.FormatSecureBox('upw')
replacements['<mm-old-pw-box>'] = list.FormatSecureBox('opw')
replacements['<mm-new-pass-box>'] = list.FormatSecureBox('newpw')
replacements['<mm-confirm-pass-box>'] = list.FormatSecureBox('confpw')
replacements['<mm-change-pass-button>'] = list.FormatButton('changepw')
replacements['<mm-form-start>'] = list.FormatFormStart('handle_opts', user)
replacements['<mm-user>'] = user
replacements['<mm-email-my-pw>'] = list.FormatButton('emailpw', 'Email my password')

doc.AddItem(list.ParseTags('options.html', replacements))
print doc.Format()
