MODERATED_LIST_MSG    = "Moderated list"
IMPLICIT_DEST_MSG     = "Implicit destination"
SUSPICIOUS_HEADER_MSG = "Suspicious header"
FORBIDDEN_SENDER_MSG  = "Forbidden sender"

MMUnknownListError   = "MMUnknownListError"
MMBadListError       = "MMBadListError"
MMBadUserError       = "MMBadUserError"
MMBadConfigError     = "MMBadConfigError"

MMBadEmailError      = "MMBadEmailError"
MMMustDigestError    = "MMMustDigestError"
MMCantDigestError    = "MMCantDigestError"
MMNotAMemberError    = "MMNotAMemberError"
MMListNotReady       = "MMListNotReady"
MMNoSuchUserError    = "MMNoSuchUserError"
MMBadPasswordError   = "MMBadPasswordError"
MMNeedApproval       = "MMNeedApproval"
MMHostileAddress     = "MMHostileAddress"
MMAlreadyAMember     = "MMAlreadyAMember"
MMPasswordsMustMatch = "MMPasswordsMustMatch"
MMAlreadyDigested    = "MMAlreadyDigested"
MMAlreadyUndigested  = "MMAlreadyUndigested"
MMBadRequestId       = "MMBadRequestId"
MMWebSubscribeRequiresConfirmation = "MMWebSubscribeRequiresConfirmation"

