#! /usr/bin/env python
# 
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# NOTE: This is being deprecated since mailman has been shifted over to an
#       external archiver (ie, andrew kuchling's latest version of pipermail.)
#
# This script gets called by cron.
# It updates the archive for all mailing lists with update-frequency equal
# to or greater than the specified archive level.


import sys
import paths
from Mailman import MailList
from Mailman import mm_cfg
from Mailman import Utils

# Work around known problems with some RedHat cron daemons
import signal
signal.signal(signal.SIGCHLD, signal.SIG_DFL)

def usage():
    sys.stderr.write("Usage: %s level\n" % sys.argv[0])
    sys.stderr.write("\twhere level is an integer, "
		     "typically 1=daily, 2=hourly")

if len(sys.argv) != 2:
    usage()
    raise SystemExit, 1
try:
    level = int(sys.argv[1])
except ValueError:
    usage()
    raise SystemExit, 1

for name in Utils.list_names():

    list = MailList.MailList(name)

    if level <= list.archive_update_frequency:
	list.UpdateArchive()
    list.Unlock()
