#!/usr/local/bin/python 
# 
# This script gets called by cron.
# It updates the archive for all mailing lists.


import sys

sys.path.append('/home/mailman/mailman/modules')

import maillist, mm_cfg

for list_name in sys.argv[1:]:

    list = maillist.MailList(list_name)
    list.UpdateArchive()
    list.Unlock()
