#!/usr/local/bin/python 
# 
# This script gets called by cron.
# It checks each list for pending requests, and mails the admin
# of that list if something needs his or her attention.

import sys, os

sys.path.append('/home/mailman/mailman/modules')

import maillist, mm_cfg, mm_message

for name in maillist.list_names():
    try:
	list = maillist.MailList(name)
    except:
	continue
    count = list.RequestsPending()
    if count:
	list.SendTextToUser(subject = '%d %s admin request(s) waiting' % 
			              (count, list.real_name),
			    recipient = list.GetAdminEmail(),
			    text = '''
	The %s mailing list has %d request(s) waiting 
	for your consideration at:
	%s
	
	Please attend to this at your earliest convenience.''' % 
			 (list.real_name, count, list.GetScriptURL('admindb')))
    list.Unlock()
