#! /usr/bin/env python
#
# Copyright (C) 1998,1999,2000 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""Process queued messages.
"""

import os

import paths
from Mailman import mm_cfg
from Mailman import Utils
from Mailman.Queue import IncomingRunner
from Mailman.Queue import OutgoingRunner
from Mailman.Queue import NewsRunner
from Mailman.Logging.Utils import LogStdErr

# Work around known problems with some RedHat cron daemons
import signal
signal.signal(signal.SIGCHLD, signal.SIG_DFL)

LogStdErr('error', 'qrunner', manual_reprime=0, tee_to_stdout=0)

QRUNNERS = [IncomingRunner.IncomingRunner,
            OutgoingRunner.OutgoingRunner,
            NewsRunner.NewsRunner,
            ]



def main():
    # run each qrunner in their own processes
    kids = {}
    for qrclass in QRUNNERS:
        pid = os.fork()
        if pid:
            # parent
            kids[pid] = pid
        else:
            # child
            qrclass().run()
            os._exit(0)
    Utils.reap(kids)



if __name__ == '__main__':
    main()
