#! /usr/bin/env python
# 
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# This script is meant to be periodically applied by cron, to dispatch
# messages pending delivery on the mailman mail queue.


import os
import sys
import paths
from Mailman import OutgoingQueue
from Mailman import flock
from Mailman import mm_cfg

# Work around known problems with some RedHat cron daemons
import signal
signal.signal(signal.SIGCHLD, signal.SIG_DFL)

def main():
    path = os.path.join(mm_cfg.LOCK_DIR, 'mmqueue_run.lock')
    lockfile = flock.FileLock(path,
                              # running the queue can take a long time
                              hung_timeout=14400)
    lockfile.lock()
    try:
        OutgoingQueue.processQueue()
    finally:
        lockfile.unlock()


main()
