#!/usr/local/bin/python 

# This script gets called by cron at 12:00 am new years day every year. 
# It bumps the volume number up by one on each list, and resets
# The digest number to 0.

import sys, os

sys.path.append('/home/mailman/mailman/modules')

import maillist, mm_cfg, mm_utils


for name in mm_utils.list_names():
    try:
	list = maillist.MailList(name)
    except:
	continue
    list.UpdateArchive()
    if list.archive_volume_frequency == 0:
	# Remove old INDEX file, as it will never be used again, and eats
	# up disk space.
	os.unlink(os.path.join(list.archive_directory, "volume_%d/INDEX" %
			       list.volume))
	list.volume = list.volume + 1
	list.next_digest_number = 1
    list.Save()
    list.Unlock()

