#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# NOTE: This is being deprecated since mailman has been shifted over to an
#       external archiver (ie, andrew kuchling's latest version of pipermail.)
#
# This script gets called by cron at 12:00 am the first of each month
# It bumps the volume number up by one on each list, and resets
# The digest number.

import sys, os
import paths
from Mailman import MailList
from Mailman import Utils

# Work around known problems with some RedHat cron daemons
import signal
signal.signal(signal.SIGCHLD, signal.SIG_DFL)

for name in Utils.list_names():
    try:
	list = MailList.MailList(name)
    except:
	continue
    list.UpdateArchive()
    if list.archive_volume_frequency == 1:
	# Remove old INDEX file, as it will never be used again, and eats
	# up disk space.
	os.unlink(os.path.join(list.archive_directory, "volume_%d/INDEX" %
			       list.volume))
	list.volume = list.volume + 1
	list.next_digest_number = 1
    list.Save()
    list.Unlock()

