#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# This is another script that's really just for my use, but
# feel free to use it if you know how...

import sys
import os
import paths
import mm_message, mm_utils

try:
    sys.stderr = mm_utils.StampedLogger("error",
                                        label = 'answer_majordomo_mail',
                                        manual_reprime=1)
except IOError:
    pass                        # Oh well - SOL on redirect, errors show thru.

msg = mm_message.IncomingMessage()
txtfile = os.path.join(paths.prefix, 'misc/majordomo.answer.txt')
text = open(txtfile, 'r').read()
mm_utils.SendTextToUser('Your mail to Majordomo...', text, msg.GetSender(),
                        'mailman-owner')
