#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""Send a message to the maillist owner.

This script gets called by the wrapper.

Stdin is the mail message, and argv[1] is the name of the mailing list
whose owner(s) to send mail to.
"""


import sys
import paths
from Mailman import MailList
from Mailman import Message
from Mailman.Logging.StampedLogger import StampedLogger

try:
    sys.stderr = StampedLogger("error", label = 'post',
                               manual_reprime=1, nofail=0)
except IOError:
    pass                        # Oh well - SOL on redirect, errors show thru.

# Only let one program run at once per list.

# TODO: This *can* fail, and should send back an error message when it does.
current_list = MailList.MailList(sys.argv[1])
try:
    msg = Message.IncomingMessage()
    if not current_list.bounce_processing or not current_list.ScanMessage(msg):
	current_list.DeliverToList(msg, current_list.owner, '', '')
# Let another process run.
finally:
    current_list.Unlock()
    
