#! /usr/bin/env python
#
# Copyright (C) 1998,1999,2000 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""Process emailed commands.

Called by the wrapper, stdin is the mail message, and argv[1] is the name
of the target mailing list.

Errors are redirected to logs/errors.
"""


import sys

import paths
from Mailman import mm_cfg
from Mailman import MailList
from Mailman import Utils
from Mailman import Message
from Mailman import Errors
from Mailman.pythonlib.StringIO import StringIO
from Mailman.Logging.Utils import LogStdErr

LogStdErr("error", "mailcmd")



def main(mlist):
    try:
        listname = sys.argv[1]
    except IndexError:
        sys.stderr.write('Mailman error: mailcmd got no listname.\n')
        sys.exit(1)
    try:
        mlist = MailList.MailList(listname, lock=0)
    except Errors.MMListError, e:
        sys.stderr.write('Mailman error: mailcmd got bad listname: %s\n%s' %
                         (listname, e))
        sys.exit(1)
    # Try to obtain the mailing list lock.  If that fails, enqueue the message
    # for delivery by the qrunner cron job.
    try:
        mlist.Lock(timeout=mm_cfg.LIST_LOCK_TIMEOUT)
    except LockFile.TimeOutError:
        msg.Enqueue(mlist)
        return
    try:
        s = StringIO(sys.stdin.read())
        msg = Message.Message(s)
        # Moved the setting of 'torequest' into MailCommandHandler
        mlist.ParseMailCommands(msg)
    finally:
        mlist.Save()
        mlist.Unlock()



if __name__ == '__main__':
    main()
