#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

"""Process emailed commands.

Called by the wrapper, stdin is the mail message, and argv[1] is the name
of the target mailing list.

Errors are redirected to logs/errors.
"""


import sys
import paths
from Mailman import MailList
from Mailman import Utils

from Mailman.Logging.Utils import LogStdErr
LogStdErr("error", "mailcmd")

# Only let one program run at once per list.

if sys.argv[1] not in Utils.list_names():
    import mm_cfg
    Utils.SendTextToUser("Misconfigured list %s" % sys.argv[1],
                         ("List %s in aliases but not among "
                          "list_names?\n\n"
                          "---------- Forwarded message ----------\n"
                          "%s"
                          % (mm_cfg.MAILMAN_OWNER, sys.stdin.read())),
                         mm_cfg.MAILMAN_OWNER,
                         sender=mm_cfg.MAILMAN_OWNER)

list = MailList.MailList(sys.argv[1])

try:
    list.ParseMailCommands()
finally:
    list.Unlock()

