#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

import sys, os
import paths
import smtplib,mm_cfg

#sys.stderr = open("/home/mailman/mailman/logs/debug","a+")
#sys.stdout = sys.stderr

from_addr = sys.argv[1]
tmp_file  = sys.argv[2]
to_addrs  = sys.argv[3:]

file = open(tmp_file, "r")
text = file.read()
file.close()
con = smtplib.SmtpConnection(mm_cfg.SMTPHOST)
con.helo(mm_cfg.DEFAULT_HOST_NAME)
con.send(to=to_addrs, frm=from_addr, text=text)
con.quit()
os.unlink(tmp_file)

