#! /usr/bin/env python
#
# Copyright (C) 1998 by the Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software 
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

SENDMAIL_CMD = '/usr/sbin/sendmail -f %s %s'
import os

if not os.fork():
    import string, sys
    def CallSendmail(cmd, stdin):
	file = os.popen(cmd, 'w')
	file.write(stdin)
	file.close()

    sender = sys.argv[2]
    to_list = sys.argv[3:]
    file = open(sys.argv[1], 'r')
    text = file.read()
    file.close()
    os.unlink(sys.argv[1])
    CallSendmail(SENDMAIL_CMD % (sender, string.join(to_list)), text)



