.\"
.\" GNU Mailman Manual
.\"
.\" check_perms 
.\"
.\" Documenter:   Terri Oda
.\"               terri (at) zone12.com
.\" Created:      September 14, 2004
.\" Last Updated: September 14, 2004
.\"
.TH check_perms 1 "September 14, 2004" "Mailman 2.1" "GNU Mailman Manual"
.\"=====================================================================
.SH NAME
check_perms \- Check the permissions for the Mailman installation.
.\"=====================================================================
.SH SYNOPSIS
.B check_perms 
[-f]
[-v]
[-h]
.\"=====================================================================
.SH DESCRIPTION
.B check_perms 
checks the permissions for the Mailman installation.
.PP
With no arguments, just check and report all the files that have bogus
permissions or group ownership.  With -f (and run as root), fix all the
permission problems found.  With -v be verbose.
.\"=====================================================================
.SH OPTIONS
.IP "-f"
Run as root and fix all the permission problems found.
.IP "-v"
Verbose output.  
.IP "--help, -h"
Print help message and exit.
.\"=====================================================================
.SH SEE ALSO
.BR check_db (1),
.BR transcheck (1)
.PP
The Mailman website: http://www.list.org
.\"=====================================================================
.SH AUTHOR
This man page was created by Terri Oda <terri (at) zone12.com>.
Use <mailman-developers@python.org> to contact the developers.
